### ISSUE TITLE
Cant save images in /static

### ISSUE THREAD

**Issue by Flosi23** [lsglab/frontend#60]
I have the issue that all the images i want to save in ./static are being deleted automatically. The images I want to save there are not temporary or might be changed in the future. They will stay the same for sure (e.g.: arrow symbol, clock symbol). 

I know that this is probably not a bug but rather intention. In case it is intention I think it should be changed cause it does make sense to save STATIC images in ./static. In case it is bug, please fix it.

**Comment by GitGangGuy** [comment]
I'm assuming you're experiencing this on the issue-53 Branch or something branching off of it. If you check the package.json file you will notice that a script called "static" is part of the build step, deleting all files in the static directory and replacing them with those from the assets/static subdirectory. This is intentional, as the static folder contains a lot of automatically generated junk/temporary files that shouldn't be committed with git (this is also why the static directory is listed in the .gitignore). Just move the images you'd like to keep permanently into the specified assets directory. :-)

**Comment by Flosi23** [comment]
Ok. Thank you a lot
