### ISSUE TITLE
feat: improve card design

### ISSUE THREAD

**Issue by Lacrimus** [lsglab/frontend#89]

**Comment by GitGangGuy** [comment]
Hi! Please open a PR so we can follow progress and review changes early. I've noticed that your latest commit to this issues branch has a pretty long scope. In such cases, omit the scope in order to keep commit messages readable. You can edit your previous commit message with `git commit --amend`. You might have to stash any work you've done locally before with `git add -A && git stash` and then `git stash pop` to paste the changes back in. Thanks!
